// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text                 string    `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Post) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Metadata struct {
	CreatedBy            string                 `protobuf:"bytes,1,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedBy            string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Metadata) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Metadata) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type InsertPostResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertPostResponse) Reset()         { *m = InsertPostResponse{} }
func (m *InsertPostResponse) String() string { return proto.CompactTextString(m) }
func (*InsertPostResponse) ProtoMessage()    {}
func (*InsertPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{2}
}

func (m *InsertPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertPostResponse.Unmarshal(m, b)
}
func (m *InsertPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertPostResponse.Marshal(b, m, deterministic)
}
func (m *InsertPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertPostResponse.Merge(m, src)
}
func (m *InsertPostResponse) XXX_Size() int {
	return xxx_messageInfo_InsertPostResponse.Size(m)
}
func (m *InsertPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertPostResponse proto.InternalMessageInfo

func (m *InsertPostResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdatePostResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{3}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

func (m *UpdatePostResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetPostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{4}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "content.Post")
	proto.RegisterType((*Metadata)(nil), "content.Metadata")
	proto.RegisterType((*InsertPostResponse)(nil), "content.InsertPostResponse")
	proto.RegisterType((*UpdatePostResponse)(nil), "content.UpdatePostResponse")
	proto.RegisterType((*GetPostRequest)(nil), "content.GetPostRequest")
}

func init() { proto.RegisterFile("content.proto", fileDescriptor_61cc9617ce0cf609) }

var fileDescriptor_61cc9617ce0cf609 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4f, 0xea, 0x40,
	0x10, 0xc6, 0x29, 0x8f, 0xf7, 0x0a, 0x43, 0x20, 0x79, 0x1b, 0x13, 0x9b, 0x1a, 0xb5, 0xd9, 0x78,
	0xe0, 0x62, 0x9b, 0xc0, 0x49, 0x6f, 0xe0, 0xc1, 0x78, 0x30, 0x31, 0x8d, 0x5e, 0xbc, 0x98, 0xa5,
	0x1d, 0xb1, 0x91, 0x76, 0x2b, 0x3b, 0x4d, 0xc0, 0x3f, 0xcc, 0xa3, 0x7f, 0x9b, 0xe9, 0x76, 0x5b,
	0x82, 0x44, 0x4f, 0x30, 0xdf, 0x7c, 0xf3, 0xf5, 0x37, 0xd3, 0xc2, 0x20, 0x92, 0x19, 0x61, 0x46,
	0x7e, 0xbe, 0x92, 0x24, 0x99, 0x6d, 0x4a, 0xf7, 0x74, 0x21, 0xe5, 0x62, 0x89, 0x81, 0x96, 0xe7,
	0xc5, 0x73, 0x40, 0x49, 0x8a, 0x8a, 0x44, 0x9a, 0x57, 0x4e, 0x2e, 0xa1, 0x73, 0x27, 0x15, 0xb1,
	0x21, 0xb4, 0x93, 0xd8, 0xb1, 0x3c, 0x6b, 0xd4, 0x0b, 0xdb, 0x49, 0xcc, 0x0e, 0xe0, 0x2f, 0x25,
	0xb4, 0x44, 0xa7, 0xad, 0xa5, 0xaa, 0x60, 0x0c, 0x3a, 0x84, 0x6b, 0x72, 0xfe, 0x68, 0x51, 0xff,
	0x67, 0xe7, 0xd0, 0x4d, 0x91, 0x44, 0x2c, 0x48, 0x38, 0x1d, 0xcf, 0x1a, 0xf5, 0xc7, 0xff, 0xfd,
	0x9a, 0xe6, 0xd6, 0x34, 0xc2, 0xc6, 0xc2, 0x3f, 0x2d, 0xe8, 0xd6, 0x32, 0x3b, 0x06, 0x88, 0x56,
	0x28, 0x08, 0xe3, 0xa7, 0xf9, 0xc6, 0x3c, 0xbd, 0x67, 0x94, 0xd9, 0x86, 0x5d, 0x6c, 0xdb, 0x82,
	0x34, 0x49, 0x7f, 0xec, 0xfa, 0xd5, 0x4a, 0x7e, 0xbd, 0x92, 0x7f, 0x5f, 0xaf, 0xd4, 0x8c, 0x4e,
	0xa9, 0x4c, 0x2e, 0xf2, 0xb8, 0x4e, 0xae, 0x78, 0x7b, 0x46, 0xa9, 0x92, 0xeb, 0xb6, 0x20, 0x83,
	0xfd, 0x6b, 0xb2, 0x71, 0x4f, 0x89, 0x9f, 0x01, 0xbb, 0xc9, 0x14, 0xae, 0xa8, 0xbc, 0x5b, 0x88,
	0x2a, 0x97, 0x99, 0xc2, 0xef, 0xf7, 0xe3, 0x3e, 0xb0, 0x07, 0x3d, 0xb2, 0xe3, 0x72, 0xc0, 0x56,
	0x45, 0x14, 0xa1, 0x52, 0xda, 0xda, 0x0d, 0xeb, 0x92, 0x7b, 0x30, 0xbc, 0x46, 0x13, 0xf9, 0x56,
	0xe0, 0xfe, 0x1b, 0x19, 0x7f, 0x58, 0x60, 0x5f, 0x55, 0x77, 0x65, 0x97, 0x00, 0x5b, 0x06, 0x36,
	0x68, 0xee, 0x5d, 0x96, 0xee, 0x51, 0x53, 0xee, 0x73, 0xf2, 0x56, 0x39, 0xbb, 0x25, 0xfb, 0x79,
	0x76, 0x9f, 0x9e, 0xb7, 0xd8, 0x04, 0x6c, 0x43, 0xc9, 0x0e, 0x1b, 0xe7, 0x2e, 0xb7, 0xbb, 0x9b,
	0xc8, 0x5b, 0x33, 0xef, 0xf1, 0x64, 0x91, 0xd0, 0x4b, 0x31, 0xf7, 0x23, 0x99, 0x06, 0x31, 0xbe,
	0xbf, 0x4a, 0x41, 0xc1, 0x3a, 0xca, 0x28, 0x33, 0xdf, 0xe5, 0x3f, 0xfd, 0x33, 0xf9, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0x0f, 0xe2, 0x77, 0xc6, 0x02, 0x00, 0x00,
}
